a = input('enter number 1 \n ')
b = input('enter number 2\n')
c = input('enter number 3\n')
d = input('enter number 4\n')
e = (int(a) + int (b) ) - (int (c) + int (d))
print(' The calculation of 4 number is' + str (e))